language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

#env:
#  - DJANGO=1.11

install:
  - pip install -U setuptools
  - # pip install coveralls
  - pip install Django==$DJANGO
  - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .
  
# command to run tests, e.g. python setup.py test
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - # if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then inv cov; fi;
  - inv prep test

# after_success:
#   - coveralls

