language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10

install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install Django==$DJANGO
  - pip install -r requirements.txt
  - pip install .

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then inv cov; fi;

after_success:
  - coveralls

